### ISSUE TITLE
Error launching browser!

### ISSUE THREAD

**Issue by scottkidder** [Cropster/ember-visual-test#2]
First of all, this is an incredible addon you've built, and I'm excited to start using it.

I've setup a basic acceptance test with the capture helper, but when running ember test I get this error:

```
Error when launching browser!
{ Error: connect ECONNREFUSED 127.0.0.1:34175
    at Object._errnoException (util.js:999:13)
    at _exceptionWithHostPort (util.js:1020:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1207:14)
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 34175 }
events.js:136
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'visual-test-output/baseline/linux-signin.png'
```

I am using mirage on ember-cli 2.18.1

Any ideas what's going on here?

**Comment by scottkidder** [comment]
I've tracked this down to [this issue in chrome-launcher](https://github.com/GoogleChrome/chrome-launcher/issues/6#issuecomment-341491690)
`--no-sandbox` is already being passed to simple-headless-chrome but only when TRAVIS or CIRCLECI env vars are present.

I was encountering this issue on Debian testing using google-chrome-beta but passing --no-sandbox to the launcher has resolved it.
