### ISSUE TITLE
Hung tests when image sizes don't match

### ISSUE THREAD

**Issue by kellyselden** [Cropster/ember-visual-test#38]
I introduced a failure on purpose to test this out, and I got:

```
(node:9604) UnhandledPromiseRejectionWarning: Error: Image sizes do not match.
    at pixelmatch (/***/node_modules/pixelmatch/index.js:19:15)
    at exports.PNG.doneReading (/***/node_modules/ember-visual-test/index.js:209:39)
    ...
```

and it hangs forever. I think there needs to be additional error handling for your call to pixelmatch.

**Comment by mydea** [comment]
Would you be willing to write a PR for this? I currently don't have time to work on this myself..!

**Comment by r3m1r0** [comment]
I proposed a PR fixing this issue : https://github.com/Cropster/ember-visual-test/pull/58
Give us a feedback if there is a problem.
