### ISSUE TITLE
User must manually create visual-test-output/{baseline,tmp,diff} directories

### ISSUE THREAD

**Issue by scottkidder** [Cropster/ember-visual-test#5]
Running tests using `capture` helper with these directories not present causes the follow error:

```
{ Error: ENOENT: no such file or directory, open 'visual-test-output/tmp/linux-signin.png'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'visual-test-output/tmp/linux-signin.png' }
(node:28093) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.join (path.js:1244:7)
    at _makeScreenshots.then.then.catch (/home/skidder/src/git/ember-visual-test/index.js:343:34)
    at <anonymous>
(node:28093) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:28093) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The addon should either create directories at runtime if needed, or create them upfront with ember-cli.

If nothing else, it should be documented that these directories must be created manually.

**Comment by mydea** [comment]
Hmm, when installed via `ember install ember-visual-test`, it should create these directories for you! Did you install it like that, and the folders were not there?

**Comment by scottkidder** [comment]
Yes I installed like that and verified on a new project.

I even tried `ember generate ember-visual-test` but that did not create the directories either.

I do however get the `.gitignore` modifications and new .npmignore file on initial install.

```
ember-cli: 2.18.2
http_parser: 2.7.0
node: 9.3.0
v8: 6.2.414.46-node.15
uv: 1.18.0
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
os: linux x64
```

**Comment by eshtadc** [comment]
I have the same experience on ember-cli 3.0.0
